export const SET_FORECASTS = "CONTENT/SET_FORECASTS";
export const DELETE_FORECASTS = "CONTENT/DELETE_FORECASTS";
export const SET_FORECASTS_SUCCESS = "CONTENT/SET_FORECASTS_SUCCESS";
export const SET_FORECASTS_ERROR = "CONTENT/SET_FORECASTS_ERROR";

export const SET_SEARCH_SUCCESS = "CONTENT/SET_SEARCH_SUCCESS";
export const SET_SEARCH_ERROR = "CONTENT/SET_SEARCH_ERROR";
export const DELETE_SEARCH_ERROR = "CONTENT/DELETE_SEARCH_ERROR";

export const SET_LOCATION = "CONTENT/SET_LOCATION";
export const SET_LOCATION_SUCCESS = "CONTENT/SET_LOCATION_SUCCESS";
export const SET_LOCATION_ERROR = "CONTENT/SET_LOCATION_ERROR";
export const DELETE_LOCATION = "CONTENT/DELETE_LOCATION";

export const SET_SINGLEFORECAST = "CONTENT/SET_SINGLEFORECAST";
export const SET_SINGLEFORECAST_SUCCESS = "CONTENT/SET_SINGLEFORECAST_SUCCESS";
export const SET_SINGLEFORECAST_ERROR = "CONTENT/SET_SINGLEFORECAST_ERROR";
export const DELETE_SINGLEFORECAST = "CONTENT/DELETE_SINGLEFORECAST";
